In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\satyam jha\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\satyam jha\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satyam jha\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\satyam jha\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\satyam jha\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\satyam jha\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
lst = [1,2,3,4,5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [5]:
pd.Series([lst,lst,lst])

0    [1, 2, 3, 4, 5]
1    [1, 2, 3, 4, 5]
2    [1, 2, 3, 4, 5]
dtype: object

In [6]:
df = pd.DataFrame([lst,lst,lst,lst,lst,lst,lst],columns = ['A','B','C','D','E'] )

In [7]:
df

   A  B  C  D  E
0  1  2  3  4  5
1  1  2  3  4  5
2  1  2  3  4  5
3  1  2  3  4  5
4  1  2  3  4  5
5  1  2  3  4  5
6  1  2  3  4  5

In [8]:
del df

In [9]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is F8A7-C319

 Directory of C:\Users\Satyam Jha\Desktop

18-03-2025  00:25    <DIR>          .
07-03-2025  15:19    <DIR>          ..
17-03-2025  02:28    <DIR>          .ipynb_checkpoints
15-03-2025  17:58            50,669 2530dd3a-d1ec-4224-a954-c0b3448b9935.pdf
30-03-2024  23:22           477,253 AI Engineer Roadmap 2024.pdf
01-01-2025  00:18             2,413 AI-Navigator.lnk
07-03-2025  15:18    <DIR>          arid
31-12-2024  21:38             1,377 CapCut.lnk
27-02-2025  14:41            74,049 Contestant journey + theme.pdf
26-10-2024  14:25    <DIR>          cpp
18-03-2025  00:25            61,214 Data_preprocessing_with_google_playstore.ipynb
12-01-2025  22:25            56,571 Football.csv
27-01-2025  01:21         1,349,314 googleplaystore.csv
07-12-2024  14:16             1,445 Grammarly.lnk
25-08-2024  04:37    <DIR>          Hack24
31-12-2024  02:02           268,766 IITG hackathonppt.pdf
09-01-2025  16:54             7,968 Inventory Management Overview JSON .ipynb
06-01-2025  16:57             9,029 Inventory Management.ipynb
06-01-2025  16:47                59 Inventory Management.txt
18-01-2025  17:57            28,532 mean_mode_median.ipynb
05-03-2025  22:41             2,363 Microsoft Edge.lnk
01-02-2024  21:21               890 MinGW Installer.lnk
24-08-2024  18:42             2,383 MongoDBCompass.lnk
08-03-2025  20:29           150,953 MSR Sample Anxiety and Depression 2023.pdf
12-01-2025  23:19                80 Numbers.csv
12-01-2025  23:46           254,901 Pandas.ipynb
08-03-2025  20:33             8,922 prescription.pdf
24-08-2024  19:14    <DIR>          pro
09-01-2025  16:26               276 Record.json
09-01-2025  16:03               272 Sales.csv
09-01-2025  16:26               365 Sales.txt
13-03-2025  23:34            39,853 Sales_GST-0270.pdf
22-11-2023  00:02             2,589 Satyam - Chrome.lnk
11-09-2024  15:19    <DIR>          sih
24-01-2025  18:32           162,039 statics.ipynb
15-03-2025  17:39             6,004 success1.jpg
31-01-2024  00:54             1,430 Visual Studio Code.lnk
15-03-2025  17:37            49,061 WhatsApp Image 2025-03-15 at 17.37.16_93e4e9b9.jpg
08-03-2025  07:02             1,977 Zoom Workplace.lnk
              31 File(s)      3,073,017 bytes
               8 Dir(s)  894,576,570,368 bytes free

In [10]:
data = pd.read_csv("googleplaystore.csv")

In [11]:
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [12]:
type(data)

pandas.core.frame.DataFrame

In [13]:
data.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [14]:
data['App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [15]:
data['Size']

0                       19M
1                       14M
2                      8.7M
3                       25M
4                      2.8M
                ...
10836                   53M
10837                  3.6M
10838                  9.5M
10839    Varies with device
10840                   19M
Name: Size, Length: 10841, dtype: object

In [16]:
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [17]:
for i in data.columns:
    print(i)

App
Category
Rating
Reviews
Size
Installs
Type
Price
Content Rating
Genres
Last Updated
Current Ver
Android Ver

In [18]:
data['App'][5]

'Paper flowers instructions'

In [19]:
data['App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [20]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [21]:
df = data.dropna()

In [22]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### DATA ANALYSIS - NUMERIC

#### Q1. Finding Average Rating

In [25]:
data['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

In [26]:
print("Average rating of these apps : " ,float(str(int(sum(data['Rating'].dropna()))/len(data['Rating']))[:4]))

Average rating of these apps :  3.62

In [27]:
len(data['Rating'])

10841

#### Q2. How many apps are there with rating 5?

In [29]:
c = 0 
for i in data['Rating']:
    if (i == 5.0):
        c += 1

print("There are",c,"applications with rating 5.")

There are 274 applications with rating 5.

#### Q2. How many apps are there with rating 4-4.5?

In [31]:
c = 0
for i in data['Rating']:
    if(i>=4.0 and i<=4.5):
        c +=1

print("There are",c,"applications with rating 4-4.5")

There are 5451 applications with rating 4-4.5

In [32]:
 for i in df['Category'].unique():
     print(i)

ART_AND_DESIGN
AUTO_AND_VEHICLES
BEAUTY
BOOKS_AND_REFERENCE
BUSINESS
COMICS
COMMUNICATION
DATING
EDUCATION
ENTERTAINMENT
EVENTS
FINANCE
FOOD_AND_DRINK
HEALTH_AND_FITNESS
HOUSE_AND_HOME
LIBRARIES_AND_DEMO
LIFESTYLE
GAME
FAMILY
MEDICAL
SOCIAL
SHOPPING
PHOTOGRAPHY
SPORTS
TRAVEL_AND_LOCAL
TOOLS
PERSONALIZATION
PRODUCTIVITY
PARENTING
WEATHER
VIDEO_PLAYERS
NEWS_AND_MAGAZINES
MAPS_AND_NAVIGATION

## Q1.Total number of categories

In [34]:
print("There are total",len(df['Category'].unique()),'Categories.')

There are total 33 Categories.

## Q2. Total apps in ART_AND_DESIGN

In [36]:
c = 0
for i in df['Category']:
    if(i == 'ART_AND_DESIGN'):
        c  += 1

print("There are total",c,'application in ART_AND_DESIGN')

There are total 61 application in ART_AND_DESIGN

## Q.3 Total number of App-Types

In [38]:
data['Type'].unique()

array(['Free', 'Paid', nan, '0'], dtype=object)

## Q4. Total number of Paid and Free Apps

In [40]:
F = 0 
for i in df['Type']:
    if(i == 'Free'):
        F += 1

print("There are total",F,'free and',end=' ')

P = 0 
for i in df['Type']:
    if(i == 'Paid'):
        P += 1

print(P,'Paid application')

There are total 8715 free and 645 Paid application

In [41]:
F

8715

In [42]:
P

645

## Q5. Percentage of free apps in the dataset

In [44]:
print(int(F/(F + P)*100), "% application are free")

93 % application are free

## Q6. Name all the Content Ratings

In [46]:
df['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [47]:
for name in df['Category'].unique():
    ct = 0
    for i in df['Category']:
        if(i == name):
            ct += 1
    print(name,": ",ct)

ART_AND_DESIGN :  61
AUTO_AND_VEHICLES :  73
BEAUTY :  42
BOOKS_AND_REFERENCE :  178
BUSINESS :  303
COMICS :  58
COMMUNICATION :  328
DATING :  195
EDUCATION :  155
ENTERTAINMENT :  149
EVENTS :  45
FINANCE :  323
FOOD_AND_DRINK :  109
HEALTH_AND_FITNESS :  297
HOUSE_AND_HOME :  76
LIBRARIES_AND_DEMO :  64
LIFESTYLE :  314
GAME :  1097
FAMILY :  1746
MEDICAL :  350
SOCIAL :  259
SHOPPING :  238
PHOTOGRAPHY :  317
SPORTS :  319
TRAVEL_AND_LOCAL :  226
TOOLS :  733
PERSONALIZATION :  312
PRODUCTIVITY :  351
PARENTING :  50
WEATHER :  75
VIDEO_PLAYERS :  160
NEWS_AND_MAGAZINES :  233
MAPS_AND_NAVIGATION :  124

In [48]:
categories = {}

for name in df['Category'].unique():
    ct = 0
    for i in df['Category']:
        if(i == name):
            ct += 1
    categories[name] = ct

In [49]:
categories

{'ART_AND_DESIGN': 61,
 'AUTO_AND_VEHICLES': 73,
 'BEAUTY': 42,
 'BOOKS_AND_REFERENCE': 178,
 'BUSINESS': 303,
 'COMICS': 58,
 'COMMUNICATION': 328,
 'DATING': 195,
 'EDUCATION': 155,
 'ENTERTAINMENT': 149,
 'EVENTS': 45,
 'FINANCE': 323,
 'FOOD_AND_DRINK': 109,
 'HEALTH_AND_FITNESS': 297,
 'HOUSE_AND_HOME': 76,
 'LIBRARIES_AND_DEMO': 64,
 'LIFESTYLE': 314,
 'GAME': 1097,
 'FAMILY': 1746,
 'MEDICAL': 350,
 'SOCIAL': 259,
 'SHOPPING': 238,
 'PHOTOGRAPHY': 317,
 'SPORTS': 319,
 'TRAVEL_AND_LOCAL': 226,
 'TOOLS': 733,
 'PERSONALIZATION': 312,
 'PRODUCTIVITY': 351,
 'PARENTING': 50,
 'WEATHER': 75,
 'VIDEO_PLAYERS': 160,
 'NEWS_AND_MAGAZINES': 233,
 'MAPS_AND_NAVIGATION': 124}

## Q1. Total number of apps in each category

In [51]:
categories = {}

for name in df['Category'].unique():
    ct = 0
    for i in df['Category']:
        if(i == name):
            ct += 1
    categories[name] = ct
    
print(categories)

{'ART_AND_DESIGN': 61, 'AUTO_AND_VEHICLES': 73, 'BEAUTY': 42, 'BOOKS_AND_REFERENCE': 178, 'BUSINESS': 303, 'COMICS': 58, 'COMMUNICATION': 328, 'DATING': 195, 'EDUCATION': 155, 'ENTERTAINMENT': 149, 'EVENTS': 45, 'FINANCE': 323, 'FOOD_AND_DRINK': 109, 'HEALTH_AND_FITNESS': 297, 'HOUSE_AND_HOME': 76, 'LIBRARIES_AND_DEMO': 64, 'LIFESTYLE': 314, 'GAME': 1097, 'FAMILY': 1746, 'MEDICAL': 350, 'SOCIAL': 259, 'SHOPPING': 238, 'PHOTOGRAPHY': 317, 'SPORTS': 319, 'TRAVEL_AND_LOCAL': 226, 'TOOLS': 733, 'PERSONALIZATION': 312, 'PRODUCTIVITY': 351, 'PARENTING': 50, 'WEATHER': 75, 'VIDEO_PLAYERS': 160, 'NEWS_AND_MAGAZINES': 233, 'MAPS_AND_NAVIGATION': 124}

## Q2. Total number of apps in each type

In [95]:
types = {}

for name in df['Type'].unique():
    ct = 0
    for i in df['Type']:
        if(i == name):
            ct += 1
    types[name] = ct
    
print(types)

{'Free': 8715, 'Paid': 645}

## Q3. Total number of apps in Content Rating

In [98]:
content_rating = {}

for name in df['Content Rating'].unique():
    ct = 0
    for i in df['Content Rating']:
        if(i == name):
            ct += 1
    content_rating[name] = ct
    
print(content_rating)

{'Everyone': 7414, 'Teen': 1084, 'Everyone 10+': 397, 'Mature 17+': 461, 'Adults only 18+': 3, 'Unrated': 1}

In [102]:
df['Category'].describe()

count       9360
unique        33
top       FAMILY
freq        1746
Name: Category, dtype: object

In [106]:
df['Reviews'].describe()

count     9360
unique    5990
top          2
freq        83
Name: Reviews, dtype: object