In [176]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer

In [162]:
df = pd.read_csv("googleplaystore.csv")
impute = SimpleImputer(missing_values = np.nan , strategy = 'mean')
impute.fit(df.iloc[ : , 2:3 ].values)
df.iloc[ : , 2:3 ] = impute.transform(df.iloc[ : , 2:3 ].values)
df = df.dropna()

## Q1. How many free apps are there in ART_AND_DESIGN?

In [36]:
df

array([['Photo Editor & Candy Camera & Grid & ScrapBook',
        'ART_AND_DESIGN', 4.1, ..., 'January 7, 2018', '1.0.0',
        '4.0.3 and up'],
       ['Coloring book moana', 'ART_AND_DESIGN', 3.9, ...,
        'January 15, 2018', '2.0.0', '4.0.3 and up'],
       ['U Launcher Lite – FREE Live Cool Themes, Hide Apps',
        'ART_AND_DESIGN', 4.7, ..., 'August 1, 2018', '1.2.4',
        '4.0.3 and up'],
       ...,
       ['Parkinson Exercices FR', 'MEDICAL', 4.193338315362443, ...,
        'January 20, 2017', '1.0', '2.2 and up'],
       ['The SCP Foundation DB fr nn5n', 'BOOKS_AND_REFERENCE', 4.5, ...,
        'January 19, 2015', 'Varies with device', 'Varies with device'],
       ['iHoroscope - 2018 Daily Horoscope & Astrology', 'LIFESTYLE',
        4.5, ..., 'July 25, 2018', 'Varies with device',
        'Varies with device']], dtype=object)

In [38]:
c = 0

for i in df:
    if(i[1] == 'ART_AND_DESIGN' and i[6] == 'Free'):
        c += 1
        
print("There are",c,'free apps from ART_AND_DESIGN')

There are 61 free apps from ART_AND_DESIGN

## Q2. How many apps are there in ART_AND_DESIGN with rating more then 4.5?

In [41]:
c = 0

for i in df:
    if(i[1] == 'ART_AND_DESIGN' and i[2] > 4.5):
        c += 1
        
print("There are",c,'apps from ART_AND_DESIGN with rating more than 4.5')

There are 22 apps from ART_AND_DESIGN with rating more than 4.5

## Q3. How many apps are there in FAMILY with rating more then 4.5 and Free?

In [48]:
c = 0

for i in df:
    if(i[1] == 'ART_AND_DESIGN' and i[2] > 4.5 and i[6] == 'Free'):
        c += 1
        
print("There are",c,'free apps from ART_AND_DESIGN which are Free with rating more than 4.5')

There are 19 free apps from ART_AND_DESIGN which are Free with rating more than 4.5

## Q4. List all the free apps with rating more then 4.5 and category is FAMILY?

In [55]:
print("*"*100)
print("    These are the free apps where Category is FAMILY with rating more than 4.5.")
print("*"*100)

for i in df:
    if(i[1] == 'ART_AND_DESIGN' and i[2] > 4.5 and i[6] == 'Free'):
        print(i[0])
print("-"*100)

****************************************************************************************************
    These are the free apps where Category is FAMILY with rating more than 4.5.
****************************************************************************************************
U Launcher Lite – FREE Live Cool Themes, Hide Apps
Kids Paint Free - Drawing Fun
Mandala Coloring Book
Photo Designer - Write your name with shapes
ibis Paint X
Superheroes Wallpapers | 4K Backgrounds
HD Mickey Minnie Wallpapers
Harley Quinn wallpapers HD
Colorfit - Drawing & Coloring
I Creative Idea
UNICORN - Color By Number & Pixel Art Coloring
PIP Camera - PIP Collage Maker
Canva: Poster, banner, card maker & graphic design
Install images with music to make video without Net - 2018
Cardi B Wallpaper
X Launcher: With OS11 Style Theme & Control Center
AJ Styles HD Wallpapers
Fantasy theme dark bw black building
Spring flowers theme couleurs d t space
----------------------------------------------------------------------------------------------------

### ******* Now, we do same questions with Pandas ********

In [92]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [96]:
df[df["Category"] == 'ART_AND_DESIGN']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,4.193338,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.200000,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.300000,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.193338,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.000000,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

## Q1. How many free apps are there in ART_AND_DESIGN?

In [116]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']
print(len(df_pr[df_pr['Type'] == 'Free']))

61

## Q2. How many apps are there in ART_AND_DESIGN with rating more then 4.5?

In [119]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']
print(len(df_pr[df_pr['Rating'] >4.5]))

22

## Q3. How many apps are there in FAMILY with rating more then 4.5 and Free?

In [137]:
df_pr = df[df['Category'] == 'FAMILY']
df_pr = df_pr[df_pr["Rating"]>4.5]
len(df_pr[df_pr['Type']=='Free'])

314

## Q4. List all the free apps with rating more then 4.5 and category is FAMILY?

In [151]:
df_pr = df[df['Category'] == 'FAMILY']
df_pr = df_pr[df_pr["Rating"]>4.5]
result = df_pr[df_pr['Type']=='Free'].values

In [157]:
for i in result:
     print(i[0])

Super ABC! Learning games for kids! Preschool apps
Candy Pop Story
Dog Run - Pet Dog Simulator
Puzzle Kids - Animals Shapes and Jigsaw Puzzles
No. Color - Color by Number, Number Coloring
Garden Fruit Legend
Piano Kids - Music & Songs
Duolingo: Learn Languages Free
Super ABC! Learning games for kids! Preschool apps
Drawing for Kids Learning Games for Toddlers age 3
Baby ABC in box! Kids alphabet games for toddlers!
Henry Danger Crime Warp
Fruit Cube Blast
Toddler Kids Puzzles PUZZINGO
Fuzzy Seasons: Animal Forest
Dog Run - Pet Dog Simulator
My Oasis - Calming and Relaxing Idle Clicker Game
Ninja Dash - Ronin Jump RPG
Monster High™ Minis Mania
Monica Toy TV
Sworkit Kids - Fitness Meets Fun
Crazy Colors: Bubbles Matching
Pino chess
Duolingo: Learn Languages Free
Animal Jam - Play Wild!
Dog Sim Online: Raise a Family
Color by Number - Draw Sandbox Pixel Art
Build a Bridge!
Find a Way: Addictive Puzzle
CompTIA Exam Training
Gymnastics Superstar - Spin your way to gold!
Hungry Hearts Diner: A Tale of Star-Crossed Souls
Dragon Sim Online: Be A Dragon
Cat Sim Online: Play with Cats
Clash of Clans
Clash Royale
Learn C++
C Programming Zone
All C Programs
codeEazy - C/C++/JAVA
C Functions
Learn Basic C - For Beginners
C Prowess
101 C Programming Problems
C BOOK-C PROGRAMS
Eternium
Harris J Lyrics
2048 BTS J Hope KPop Puzzle Game
J. Cole Albums (2007-2017)
K-Otic Universe
CASE K-12 Math English Science
K-Spapp, the K-Space app
EXO-L
Fantastic Chefs: Match 'n Cook
Twitch: Livestream Multiplayer Games & Esports
Channel U
Get Free V-bucks_fortnite Hints
Easy V-Bux free
X-Wing Squadron Builder
JW Caleb y Sofia
PewDiePie's Tuber Simulator
Z-Empire: Dead Strike
Angry Birds Blast
Angry Birds Match
Angry Birds 2
Alchemy Classic Ad Free
Nasihat - Chalo ae Pyaara
9GAG: Funny Gifs, Pics, Memes & Videos for IGTV
Orbita AI — Exciting mobile puzzles & riddles
Learn Artificial Intelligence
Animal Jam - Play Wild!
AJ Official
Little Pets Animal Guardians
AJ Rafael Music Lessons
Weapon stripping 3D
Al jazeera TV
Al Quran Audio (Full 30 Juz)
Quran for All (Al-Huda Int.)
Ayat - Al Quran
Quran Juz-30 - Mahad al Zahra
Al Quran MP3 - Quran Reading®
Al-Quran Ahmad Saud Offline
Virtual lover
virtual lover 3D
Bubbu – My Virtual Pet
AP® Guide
AP Mobile
Study AP World History
AP Chemistry Prep: Practice Tests and Flashcards
AP World History: Practice Tests and Flashcards
AP Biology Prep: Practice Tests, Flashcards
AP European History: Practice Tests and Flashcards
Adventure Quest World Mobile Quiz
AQ Ria Retail
Accounting Quiz (AQ) Malaysia
Wowkwis aq Ka'qaquj
Questland: Turn Based RPG
Grow Stone Online : 2d pixel RPG, MMORPG game
Egg, Inc.
Choices: Stories You Play
Aw Restaurant
AW Training
Anime Expo 2018
INTERACTIVE CALCULUS FOR MATHS AND PHYSICS
Pinoy Kid Song Ako ay may Lobo
Quran Khmer Offline AY
Permit Test AZ Arizona MVD DOT
Catalyst AZ
Az Video Status
Goody.ba
Learn alif ba ta
Arabic Alphabet Alif Ba Ta Wooden Blocks
Let's Learn Alif Ba Ta
Sufara.ba
Elif Ba - Learn The Holy Quran
Elifba Quran Learning Game
Railroad Radio Vancouver BC
BD Online Passport Application
BD Hospital's
Exam Result BD
BG Future School
Learn Bulgarian Free
Bh Public School
BH Challenge - Museum of the Jewish People
Bitmoji – Your Personal Emoji
Business Intelligence & Data
TED
English Grammar Test
HON. B.J. ACS COLLEGE ALE
BK Video Status
Audio Murli Glossary For BK
Baba Yaad Hai?(BK's)
BK murli today (Mobile Murli) - Gyan
BK Murli Dictionary (H to E)
BkEmu - BK-0010/11M emulator
Cerulean Heart
あなカレ【BL】無料ゲーム
BM SPM Practice
Township
Blood Pressure Diary
RoboPad
Br Shafi
Companion for Fortnite & Fortnite Battle Royale
Vlogger Go Viral - Tuber Game
Loved by King Bs
BS CS IT & SE
Marked by King Bs
COMSATS BOOK STORE FOR BS(CS)
Beauty Rental Shop
Sleeping Delivery
Wifi BT Scanner
BU Study
Barisal University App-BU Face
BU Students' Rep. Council
BU Calculator
BV Sridhara Maharaj
Quadratic Equation Solver with Steps and Graphs
Sandbox - Color by Number Coloring Pages
Sandbox Art-Sandbox Color by Number Coloring Pages
Color By Number - Sandbox Pixel Coloring Book
PixelDot - Color by Number Sandbox Pixel Art
PixPanda - Color by Number Pixel Art Coloring Book
Pixyfy: coloring by number coloring book
Draw Color by Number - Sandbox Pixel Art
Butterfly Pixel Art - coloring by number
Color by Number: Pixel Art
UNICORN - Color By Number & Pixel Art Coloring
FunnyPixels - Color by number Sandbox
No.Diamond – Colors by Number
Park Limousine: Realistic Limo Parking Simulator
CB News
CB Register
CD CHOICE TUBE
Yazdani Cd Center EllahAbad Official App
MCQ CE IT
Magana Jari ce Littafi Na Uku : Part 3 of 3
CF Life
All Info about Cg
CG FM
CG - Chemistry free
CG Jobs
BF CG Abstract Pictures
CI Dictionary
Sir C J New Primary School
Louis CK
Tic Tac CK
Castle Clash: Heroes of the Empire US
Cartoon Network Match Land
Super Slime Blitz - Gumball
Surely You Quest - Magiswords
We Bare Bears Match3 Repairs
Champions and Challengers - Adventure Time
CN Resident
CP Channel
Foothills CP
Cp Calculator for Evolution:GO
ClanManagerTT2
Christian Questions Podcast
CR & CoC Private Server - Clash Barbarians PRO
Ultimate Clash Royale Tracker
Servidor Privado de CR y CoC - Light Royale
Deck Shop for Clash Royale
Cr Aviation Academy
CS Interview Questions (TechQ)
DU CS Lectures - Learn to Code for Free
CS & IT Interview Questions
CA CS Network
CT Scan Generations
CT Brain Interpretation
Permit Test Connecticut CT DMV
Cy-Reader
MadLipz
DB Tools
DB for Hustle Castle
MARVEL Future Fight
DC N COMPANY ENTERTAINMENT RADIO!
Driver Permit Test Prep DC DMV Driver's License Ed
Coloring Book for Me & Mandala
Anime Love Story Games: ✨Shadowtime✨
DH-UFO
Idle Heroes
Duolingo: Learn Languages Free
PK and DK Audio App
dk
Account Class-12 Solutions (D K Goel) Vol-2
DL Hughley
DM Buddy » Learn Digital Marketing
Disciple Maker’s (DM) Lab
DN Employee
Dragon Nest M
CritDice - Dice Roller
Maher EL Mouaikly - Offline
Darkness Rises
Latest DP and Status Pro 2018
Faceoff DP Battle App
RPG Dragon Lapis
DQSalmaan - A fan made App
DS
MegaN64 (N64 Emulator)
DS-Students
DT Driving Test Theory
WPBS-DT
Du Chinese – Mandarin Lessons
DV ASSIST
DV Lottery Simulator
DV-2019 UK/British
DW Audio
German Listening
Piczle Lines DX
DX Simulation for OOO Dx Belt
DX Simulation for Kabuto Henshin Belt 2018
DX Simulation for Double Dx Henshin Belt 2018
KPS CHAUHAN DY/DX
DYPSOET
Typical EA Game
EC Calgary
EC Fairgrounds
GATE Syllabus for EC 2018 & Notifications
English Conversation Courses
Dance Magic Fashion Style Games
EI国际
TeamWard – live help for LoL
Master E.K
Ek Onkar
Pyaar Ek Dhoka
Ek Bander Ne Kholi Dukan
Toilet Ek Prem Katha Songs Lyrics in Hindi
Sanu Ek Pal Chain Song Videos - RAID Movie Songs
Ek Qissa He Quran Se (Qurani Waqiyat)
Lyrics of Ek Paheli Leela
Exiled Kingdoms RPG
Shabad Gurubani Punjabi mp3 free - Ek Onkar Satnam
El Falı
OWLIE BOO
Narcos: Cartel Wars
Hello English: Learn English
Learn Top 300 English Words
Masha and the Bear. Games for kids
Masha and The Bear Jam Day Match 3 games for kids
Masha and the Bear: Good Night!
EP Radio
Super Doctor 2 - My Newborn Baby ER Injection
Open Heart Surgery Hospital ER: Crazy Doctor Sim
YEBIS OpenGL ES 3.0 Tech Demo
Advanced calculator fx 991 es plus & 991 ms plus
Castle Clash: Epic Empire ES
School scientific calculator fx 500 es plus 500 ms
Lettre et demande d'emploi
daskal.eu
PokeType - Dex
Pink Guy - Ey B0ss
Ey Sey Storytime រឿងនិទានតាឥសី
Fallout Shelter
Story Time FD
FD VR Music Videos - MTV Pop and Rap in 360
Fire Emblem Heroes
Safe Santa Fe
POLARIS 2MFG
Puzzles Volvo FH 16 Trucks
Jigsaw Volvo FH 16 Trucks
FH School
FK Željezničar Izzy
Permit Test FL Florida DHSMV
FL Lottery Results
Scratch-Off Guide for FL Lotto
Canvas FL
Florida Wildflowers
How it Works: FN SCAR assault rifle
Ninja FN Button
Pin-fo
Fr Ignacio Outreach
Castle Clash: RPG War and Strategy FR
Fr. Daoud Lamei
Fr. Mike Schmitz Audio Teachings

# GroupBy in Pandas

In [178]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

## Q1. Name the apps that are in ART_AND_DESIGN with rating more then 4.5 in descending order WRT Ratings?

In [167]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']
df_pr = df_pr[df_pr['Rating'] > 4.5]

df_pr.sort_values( by = 'Rating', ascending = True ).head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
4764,X Launcher Prime: With OS Style Theme & No Ads,ART_AND_DESIGN,4.7,149,3.5M,"1,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",1.2.2,4.1 and up

## Q2. Which category is having maximum average rating Descending order?

In [194]:
df.groupby('Category')[['Rating']].mean().sort_values(by = 'Rating', ascending = False)

                       Rating
Category
EDUCATION            4.387778
ART_AND_DESIGN       4.368438
EVENTS               4.363647
BOOKS_AND_REFERENCE  4.311537
PERSONALIZATION      4.306873
GAME                 4.282506
PARENTING            4.282223
HEALTH_AND_FITNESS   4.266296
BEAUTY               4.260882
SHOPPING             4.254052
SOCIAL               4.248001
WEATHER              4.239675
SPORTS               4.218404
PRODUCTIVITY         4.208287
HOUSE_AND_HOME       4.196819
FAMILY               4.192490
PHOTOGRAPHY          4.192179
AUTO_AND_VEHICLES    4.190824
MEDICAL              4.190167
LIBRARIES_AND_DEMO   4.182938
FOOD_AND_DRINK       4.170709
COMMUNICATION        4.163842
COMICS               4.156445
BUSINESS             4.145987
NEWS_AND_MAGAZINES   4.142993
FINANCE              4.139108
ENTERTAINMENT        4.126174
TRAVEL_AND_LOCAL     4.119716
LIFESTYLE            4.112427
VIDEO_PLAYERS        4.074858
TOOLS                4.065970
MAPS_AND_NAVIGATION  4.065061
DATING               4.007864

## Q3. How many paid apps are there in each category in Descending Order?

In [197]:
df_pr = df[df['Type'] == 'Paid']

df_pr.groupby('Category').count()['Type'].sort_values(ascending = False)

Category
FAMILY                 190
MEDICAL                109
GAME                    83
PERSONALIZATION         82
TOOLS                   77
BOOKS_AND_REFERENCE     28
PRODUCTIVITY            28
COMMUNICATION           27
SPORTS                  24
PHOTOGRAPHY             22
LIFESTYLE               19
FINANCE                 17
HEALTH_AND_FITNESS      16
BUSINESS                14
TRAVEL_AND_LOCAL        12
WEATHER                  8
DATING                   7
MAPS_AND_NAVIGATION      5
EDUCATION                4
VIDEO_PLAYERS            4
AUTO_AND_VEHICLES        3
SOCIAL                   3
ART_AND_DESIGN           3
NEWS_AND_MAGAZINES       2
PARENTING                2
FOOD_AND_DRINK           2
SHOPPING                 2
ENTERTAINMENT            2
LIBRARIES_AND_DEMO       1
EVENTS                   1
Name: Type, dtype: int64